apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  labels:
    app: todo-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: api
        image: nginx:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_CONNECTION_STRING
          value: "Server=todo-db;Port=5432;Database=todo;User Id=postgres;Password=postgres;"
        - name: CONFIG_FILEPATH
          value: "/config/api-config.json"
        volumeMounts:
        - name: api-config
          mountPath: "/config"
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
      volumes:
      - name: api-config
        configMap:
          name: api-config